config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing#index"

  resource :signup, only: %i[ create show ], controller: "users"
  resource :sign_in, only: %i[ create show ], controller: "sessions"

  resource :forgot_password, only: :new, controller: "passwords"
  resource :password, only: %i[ create update edit ], controller: "passwords"

  scope ":user_id" do
    get "/", to: "projects#index", as: :home

    resources :projects do
      resources :tasks, except: :index
    end

    resource :sign_out, only: :destroy, controller: "sessions"
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user

  before_validation :set_user, :set_default_due_date, on: :create

  validates :title, :project_id, :user_id, presence: true

  normalizes :description, with: -> (description) { description.blank? ? nil : description }

  private

  def set_user
    self.user ||= Current.user
  end

  def set_default_due_date
    self.due_date ||= Date.today
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @task = Task.new
    @task.due_date = Date.today
  end

  def edit
  end

  def create
    task = new_task

    if task.save
      redirect_to_project
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to project_task_path(Current.user, @project, @task)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to_project
  end

  private

  def set_project
    @project = Current.user.projects.find_by(id: params[:project_id])

    unless @project
      redirect_to projects_path(Current.user)
    end
  end

  def set_task
    @task = @project.tasks.find_by(id: params[:id])

    unless @task
      redirect_to project_path(Current.user, @project)
    end
  end

  def new_task
    @project.tasks.build(task_params)
  end

  def redirect_to_project
    redirect_to project_path(Current.user, @project)
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :completed)
  end
end

app/views/tasks/edit.html.erb
<% content_for :title, "Editing #{@task.title}" %>
<div class="max-w-screen-lg mx-auto">
  <h1 class="text-center mt-4">Edit Task</h1>

  <div class="form-container">
    <%= form_with model: @task, url: project_task_path do |form| %>
      <%= render "shared/form_flash", object: form.object %>
      <div>
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, required: true, class: "input" %>
      </div>
      <div>
        <%= form.label :description, class: "label" %>
        <%= form.text_area :description, rows: 3, class: "input" %>
      </div>
      <div>
        <%= form.label :due_date %>
        <%= form.date_field :due_date, min: Date.today, class: "input" %>
      </div>
      <div class="field">
        <%= form.label :completed %>
        <%= form.check_box :completed %>
      </div>
      <div>
        <%= form.submit 'Save Changes', class: 'btn-primary' %>
        <%= link_to 'Cancel', project_path(Current.user, @project), class: 'btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>
<div class="max-w-screen-lg mx-auto">
  <h1 class="text-center mt-4">Create New Task</h1>

  <div class="form-container">
    <%= form_with model: @task, url: project_tasks_path do |form| %>
      <%= render "shared/form_flash", object: form.object %>
      <div>
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, required: true, class: "input" %>
      </div>

      <div>
        <%= form.label :description, class: "label" %>
        <%= form.text_area :description, rows: 3, class: "input" %>
      </div>

      <div>
        <%= form.label :due_date %>
        <%= form.date_field :due_date, min: Date.today, class: "input" %>
      </div>

      <%= form.submit "Create Task", class: "btn-primary" %>
      <%= link_to 'Back', project_path(Current.user, @project), class: 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% content_for :title, @task.title %>
<div class="max-w-screen-lg mx-auto">
  <h1 class="text-center mt-4"><%= @task.title %></h1>
  <div class="form-container">

    <p>
      <strong><%= @task.completed ? "Completed" : "Incomplete" %></strong>
    </p>

    <p>
      <strong>Description:</strong> <%= @task.description || 'No description provided' %>
    </p>

    <p>
      <strong>Due:</strong> <%= @task.due_date.strftime('%B %d, %Y') %>
    </p>

    <div class="flex">
      <%= link_to 'Edit', edit_project_task_path(Current.user, @project, @task), class: 'btn-primary' %>
      <%= button_to 'Delete', project_task_path(Current.user, @project, @task), data: { turbo_confirm: 'Are you sure?' }, method: :delete, class: 'btn-primary' %>
      <%= link_to 'Back', project_path(Current.user, @project), class: 'btn-primary' %>
    </div>
  </div>
</div>