config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing#index"

  resource :signup, only: %i[ create show ], controller: "users"
  resource :sign_in, only: %i[ create show ], controller: "sessions"

  resource :forgot_password, only: :new, controller: "passwords"
  resource :password, only: %i[ create update edit ], controller: "passwords"

  scope ":user_id" do
    get "/", to: "projects#index", as: :home

    resources :projects do
      resources :tasks, except: :index
    end

    resource :sign_out, only: :destroy, controller: "sessions"
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!

  layout "landing"

  def index
  end
end

app/views/landing/index.html.erb
<div class="max-w-sm mx-auto mt-32 text-center">
  <img class="max-w-48 mx-auto" src="<%= asset_path("logo-coloured.svg") %>" alt="Taskodoro logo">
  <div>
    <h1 class="font-normal mx-0 mb-0"><%= t("landing.welcome") %></h1>
    <h1 class="text-primary-gradient font-bold"><%= t("app_name") %></h1>
  </div>
  <div>
    <a class="btn" href="<%= sign_in_path %>">
      <%= t("auth.signin") %>
    </a>
    <a class="btn" href="<%= signup_path %>">
      <%= t("auth.signup") %>
    </a>
  </div>
</div>