config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing#index"

  resource :signup, only: %i[ create show ], controller: "users"
  resource :sign_in, only: %i[ create show ], controller: "sessions"

  resource :forgot_password, only: :new, controller: "passwords"
  resource :password, only: %i[ create update edit ], controller: "passwords"

  scope ":user_id" do
    get "/", to: "projects#index", as: :home

    resources :projects do
      resources :tasks, except: :index
    end

    resource :sign_out, only: :destroy, controller: "sessions"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, -> { order(:due_date) }, dependent: :destroy

  validates :title, :user_id, presence: true

  normalizes :description, with: -> (description) { description.blank? ? nil : description }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Current.user.projects.all
  end

  def show
    @tasks = @project.tasks.all
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    project = Current.user.projects.build(project_params)

    if project.save
      redirect_to_project project
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to_project @project
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to_projects
    else
      render :show
    end
  end

  private

  def set_project
    @project = Current.user.projects.find_by(id: params[:id])

    unless @project
      redirect_to_projects
    end
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def redirect_to_projects
    redirect_to projects_path(Current.user)
  end

  def redirect_to_project(project)
    redirect_to project_path(Current.user, project)
  end
end

app/views/projects/_project.html.erb
<%# locals: (project:) %>

<%= link_to project.title, project_path(Current.user, project) %><% if project.description %> — <%= project.description %><% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Editing #{@project.title}" %>
<div class="max-w-screen-lg mx-auto">
  <h1 class="text-center mt-4">Edit Project</h1>

  <div class="form-container">
    <%= form_with model: @project, url: project_path(Current.user, @project) do |form| %>
      <%= render "shared/form_flash", object: form.object %>
      <div>
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, required: true, class: "input" %>
      </div>
      <div>
        <%= form.label :description, class: "label" %>
        <%= form.text_area :description, rows: 3, class: "input" %>
      </div>
      <div>
        <%= form.submit 'Save Changes', class: 'btn-primary' %>
        <%= link_to 'Cancel', project_path(Current.user, @project), class: 'btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Home" %>
<div class="max-w-screen-lg mx-auto">
  <h1><%= Current.user.name %>'s Projects</h1>
  <section>
    <% unless @projects.empty? %>
      <ul>
        <% @projects.each do |project| %>
          <li><%= render 'projects/project', project: project %></li>
        <% end %>
      </ul>
    <% end %>
    <%= link_to 'New Project', new_project_path(Current.user), class: 'btn-primary' %>
    <%= button_to 'Log out', sign_out_path(Current.user), method: :delete, class: 'btn-primary' %>
  </section>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New Project" %>
<div class="max-w-screen-lg mx-auto">
  <h1 class="text-center mt-4">Create New Project</h1>

  <div class="form-container">
    <%= form_with model: @project do |form| %>
      <%= render "shared/form_flash", object: form.object %>
      <div>
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, required: true, class: "input" %>
      </div>

      <div>
        <%= form.label :description, class: "label" %>
        <%= form.text_area :description, rows: 3, class: "input" %>
      </div>

      <%= form.submit "Create Project", class: "btn-primary" %>
      <%= link_to 'Back', projects_path(Current.user), class: 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :title, @project.title %>
<div class="max-w-screen-lg mx-auto">
  <h1 class="text-center mt-4"><%= @project.title %></h1>
  <div class="form-container">
    <p>
      <strong>Description:</strong> <%= @project.description || 'No description provided' %>
    </p>

    <p>
      <strong>Created at:</strong> <%= @project.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
    </p>

    <p>
      <strong>Updated at:</strong> <%= @project.updated_at.strftime('%Y-%m-%d %H:%M:%S') %>
    </p>

    <div class="flex">
      <%= link_to 'Edit', edit_project_path(Current.user, @project), class: 'btn-primary' %>
      <%= button_to 'Delete', project_path(Current.user, @project), data: { turbo_confirm: 'Are you sure?' }, method: :delete, class: 'btn-primary' %>
      <%= link_to 'Back', projects_path(Current.user), class: 'btn-primary' %>
    </div>

    <h2 class="flex">Tasks (<%= @tasks.count %>)</h2>
    <%= link_to 'New Task', new_project_task_path(Current.user, @project), class: 'btn-primary' %>

    <ul>
      <% @tasks.each do |task| %>
        <li>
          <%= link_to task.title, project_task_path(Current.user, @project, task) %> - <%= task.completed ? "Completed" : "Incomplete" %>
          <p><%= task.description %></p>
          <p>Due: <%= task.due_date.strftime("%B %d, %Y") %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>